services:
  postgres:
    image: postgres:16
    container_name: zapier-postgres
    ports:
      - "5435:5432"   # ðŸ‘ˆ NEW PORT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zapier
